### ISSUE TITLE
Display size changed

### ISSUE THREAD

**Issue by caiostob** [oreo-victara/android_device_motorola_victara#2]
After 8/11 build, the display size changed, and the default became small. To solve this problem, I had to change to "Larger", to return to normal.

**Comment by jujulechti** [comment]
Till the first build, the phone crashes almost every time I enable and disable USB tethering

**Comment by caiostob** [comment]
@Andersonmendes2016

**Comment by Andersonmendes2016** [comment]
I do not remember change the density of the screen...

**Comment by caiostob** [comment]
@Andersonmendes2016 https://imgur.com/a/tG3l0
