### ISSUE TITLE
Bluetooth issues in 02/11 and 08/11 builds

### ISSUE THREAD

**Issue by jujulechti** [oreo-victara/android_device_motorola_victara#4]
So to clarify the situation with Bluetooth,

08/11 build : (I tried multiple times w/ clean flashes and aptX_arm_blobs.zip)
      It can connect, play sound like ringtones, 
      notifications, lock screen sound but nothing like 
      music or yt videos I tried to flash the
      AptX_arm_blobs.zip but still the      
      same issue. I can select the aptX codec in setting 
      but it switch back immediately to SBC every time I 
      try to modify it. (Logcat attached, lot of media server 
      errors and stuff)

14/10 build: 
       With a bit of patience, you can connect to Bluetooth 
       but  you have to wait a few seconds for it to start 
       broadcasting music, the Bluetooth codecs used    
       here are the same that in the 08/11 build.

[2017-11-09-21-10-43zip2.txt](https://github.com/oreo-victara/android_device_motorola_victara/files/1459159/2017-11-09-21-10-43zip2.txt)

**Comment by jujulechti** [comment]
UPDATE 12/11 : Some lucky users can enjoy bluetooth music playback. For myself it is still the exact same issue : I can call through my Bluetooth speaker, dailer sound are play on the BT speaker as well BUT when it come to YouTube, Spotify or anything else the speaker doesn't makes a sound :/

**Comment by Andersonmendes2016** [comment]
OK

**Comment by jujulechti** [comment]
Plus when playing music, I can't change the media volume, the phone struggles to respond when I hit vol buttons, then I tried to flash AptX_blobs_arm.zip but still no music, I tried to force aptX codec in dev settings but it goes back to SBC on its own ! I can use the hardware buttons of my speaker to pause or skip music tho.

Here is a catlog taken when trying to play music on BT speaker with the 12/11 build and AptX_blobs_arm.zip installed : 

[2017-11-13-22-13-29.txt](https://github.com/oreo-victara/android_device_motorola_victara/files/1468642/2017-11-13-22-13-29.txt)

**Comment by jujulechti** [comment]
So I asked on the xda thread people if BT music playback was working and what was their model of moto x, the results will be updated :
    XT 1092 : 2 said Broken
    XT 1085 : 1 said Broken 
    XT 1093 : not tested 
    XT 1095 : not tested 
    XT 1096 : not tested 
    XT 1097 : 1 said working and one said broken

**Comment by Andersonmendes2016** [comment]
@jujulechti can do some tests for me?

**Comment by jujulechti** [comment]
yes i would be very happy to help !!!

**Comment by jujulechti** [comment]
yes i would be very happy to help !!!

**Comment by jujulechti** [comment]
@Andersonmendes2016  yes i would be very happy to help !!!

**Comment by Andersonmendes2016** [comment]
https://drive.google.com/file/d/1enr-geSM7miYkBsZ8aIM0de1OxazTA3t/view?usp=sharing
flash and check audio bt pls

**Comment by jujulechti** [comment]
@Andersonmendes2016 Doing a backup, i test it

**Comment by jujulechti** [comment]
@Andersonmendes2016 I dirty flashed it on top of my 12/11 build and still no music from my BT speacker, i'm trying a clean flash and the .zip

**Comment by Andersonmendes2016** [comment]
try with this too https://drive.google.com/file/d/1gR95Kv1SBJh2rEHYwz7nFWTGp392JdvS/view?usp=sharing

**Comment by Andersonmendes2016** [comment]
and finally try that one. I hope it works.

https://drive.google.com/file/d/1FLUCfy3irfrfezX65NQq8WnCe0l1Ilnj/view?usp=sharing

**Comment by jujulechti** [comment]
@Andersonmendes2016 ohhhhh yes the last one is working ! so you can add it to the next build or i can upload it on the xda tread and i give you the feedback before closing this issue

**Comment by Andersonmendes2016** [comment]
@jujulechti thanks for testing it :+1:

**Comment by Andersonmendes2016** [comment]
I'll do a new build.

**Comment by JoeSchr** [comment]
@jujulechti did you do a full wipe with the working image or is a dirty flash enough?

**Comment by jujulechti** [comment]
@JoeSchr Just flash the 18/11 build https://androidfilehost.com/?fid=962021903579493516

**Comment by JoeSchr** [comment]
but did you do a dirty wipe? I'm just a little sick of setting up my device
everytime. I'm coming from lineage os 14.1

**Comment by jujulechti** [comment]
@JoeSchr you have to do a clean flash sorry for your data
