### ISSUE TITLE
HDR mode not working

### ISSUE THREAD

**Issue by jujulechti** [oreo-victara/android_device_motorola_victara#5]
When capturing a pictue with the HDR mode, it runs into a camera connexion error.

logcat : [2017-11-19-00-44-41.txt](https://github.com/oreo-victara/android_device_motorola_victara/files/1485146/2017-11-19-00-44-41.txt)

**Comment by Andersonmendes2016** [comment]
hal1 is partially functional ... we have to wait for lineage to fix HDR and camcorder.

**Comment by jujulechti** [comment]
@Andersonmendes2016 ok i will wait !
